apiVersion: v1
kind: Service
metadata:
  name: externalip-svc
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 80
  externalIPs:
  - 192.168.0.101
